spring:
  # DB 접속 정보 설정
  datasource:
    url: jdbc:mysql://localhost:3306/loginDB?serverTimezone=Asia/Seoul
    username: login_user
    password: justiff0801
    driver-class-name: com.mysql.cj.jdbc.Driver
  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb

  # JPA 설정
  jpa:
    hibernate:
#      ddl-auto: create
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 326048053675-7v7efv49t2mcodd6n0qiddtj8ob785kf.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

          kakao:
            client-id: 69bd5e701e2ed0cb9e08f3e4a847967f
            client-secret: 9aP8gFqWVUOT5kB2uowpYkmGNVx7hZc3
            scope:
              - account_email
              - profile_nickname
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-name: Kakao
            client-authentication-method: client_secret_post

          naver:
            client-id: aMyPNmgYAWCmv8tZhPpU
            client-secret: afIbNaTDA0
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

          facebook:
            client-id: 983431486559801
            client-secret: 346474d203f15ffe51b06749d5521ced
            scope:
              - email
              - public_profile

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

